### ISSUE TITLE
SyntaxError: 'async' is now a reserved word in Python 3.7

### ISSUE THREAD

**Issue by cclauss** [ibm-iotf/connector-cloudant#1]
flake8 testing of https://github.com/ibm-watson-iot/connector-cloudant on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./connector/connector-cloudant.py:113:65: E999 SyntaxError: invalid syntax
		self._cloudantAccount = cloudant.Account(self.dbUsername, async=True)
                                                                          ^
1     E999 SyntaxError: invalid syntax
1
```

**Comment by durera** [comment]
Now that cloudant connector is a feature inside the platform I’ll look at turning this repo into a tutorial/sample built around the features that are in the platform rather than standalone application code, which predates the built-in cloudant connector inside wiotp.
